// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrkdqdlclgahhztbeihe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indya2RxZGxjbGdhaGh6dGJlaWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjQ1MDYsImV4cCI6MjA2NDIwMDUwNn0.MdOKvo0CIczCJtXQO4zEfYN5qjj5EW2390WjaMTjYgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);