// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtlaxxfcwghxxmtqthne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0bGF4eGZjd2doeHhtdHF0aG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDM5NzYsImV4cCI6MjA2NTQ3OTk3Nn0.FmtNMlR8q4-RtMEsMfMQxcR1f_9b5S0M0ZjzVcrp-YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);